Font:
  normal:
	family: JetbrainsMono Nerd Font

import:
  - /home/brunovsky/.config/alacritty/dracula.yml

env:
  TERM: xterm-256color

window:
  opacity: 0.9
  enable_rgb: true


key_bindings:
  - {key: V, mods: Control|Shift, action: Paste}
  - {key: C, mods: Control|Shift, action: Copy}
  - {key: Insert, mods: Shift, action: PasteSelection}
  - {key: Equals, mods: Control, action: IncreaseFontSize}
  - {key: Minus, mods: Control, action: DecreaseFontSize}
  - {key: Paste, action: Paste}
  - {key: Copy, action: Copy}
  - {key: L, mods: Control, action: ClearLogNotice}
  - {key: L, mods: Control, chars: "\x0c"}
  - {key: PageUp, mods: Shift, action: ScrollPageUp, mode: ~Alt}
  - {key: PageDown, mods: Shift, action: ScrollPageDown, mode: ~Alt}
  - {key: Home, mods: Shift, action: ScrollToTop, mode: ~Alt}
  - {key: End, mods: Shift, action: ScrollToBottom, mode: ~Alt}
