-- return {
-- 	"yetone/avante.nvim",
-- 	event = "VeryLazy",
-- 	version = false, -- Never set this value to "*"! Never!
-- 	opts = {
-- 		provider = "copilot", -- default provider
-- 		max_context_lines = 150, -- reduce how many lines of context Avante sends
-- 		max_prompt_tokens = 7000, -- keep under your 8k TPM free-tier limit
--
-- 		providers = {
-- 			copilot = {
-- 				api_key_name = "GITHUB_TOKEN", -- Copilot plugin handles auth automatically
-- 				model = "gpt-4o",
-- 			},
-- 			openai = {
-- 				endpoint = "https://api.openai.com/v1",
-- 				model = "gpt-4o",
-- 				timeout = 30000, -- ms
-- 				extra_request_body = {
-- 					temperature = 0,
-- 					max_completion_tokens = 8192,
-- 					-- reasoning_effort = "medium", -- low|medium|high (optional)
-- 				},
-- 			},
-- 			groq = {
-- 				__inherited_from = "openai",
-- 				api_key_name = "GROQ_API_KEY",
-- 				endpoint = "https://api.groq.com/openai/v1/",
-- 				model = "openai/gpt-oss-120b",
-- 			},
-- 		},
-- 	},
--
-- 	build = "make",
-- 	dependencies = {
-- 		"nvim-treesitter/nvim-treesitter",
-- 		"stevearc/dressing.nvim",
-- 		"nvim-lua/plenary.nvim",
-- 		"MunifTanjim/nui.nvim",
-- 		"echasnovski/mini.pick",
-- 		"nvim-telescope/telescope.nvim",
-- 		"hrsh7th/nvim-cmp",
-- 		"ibhagwan/fzf-lua",
-- 		"nvim-tree/nvim-web-devicons",
-- 		"zbirenbaum/copilot.lua",
-- 		{
-- 			"HakonHarnes/img-clip.nvim",
-- 			event = "VeryLazy",
-- 			opts = {
-- 				default = {
-- 					embed_image_as_base64 = false,
-- 					prompt_for_file_name = false,
-- 					drag_and_drop = { insert_mode = true },
-- 					use_absolute_path = true, -- required for Windows
-- 				},
-- 			},
-- 		},
-- 		{
-- 			"MeanderingProgrammer/render-markdown.nvim",
-- 			opts = { file_types = { "markdown", "Avante" } },
-- 			ft = { "markdown", "Avante" },
-- 		},
-- 	},
-- }
