[default_session]
startup_command = "nvim +GoToFile"
startup_command_ignore_dirs = ["~/repos", "~/.config"]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "/ect/hosts"
path = "/etc"
startup_command = "sudo nvim hosts"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "sesh config"
path = "~/dotfiles/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/dotfiles/sesh/sesh.toml"


[[session]]
name = "lazy plugins"
path = "~/.local/share/nvim/lazy"
startup_command = "sesh connect (ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:70,border-none) && exit"
