[[session]]
name = "/ect/hosts"
path = "/etc"
startup_command = "sudo nvim hosts"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "sesh config"
path = "~/dotfiles/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/dotfiles/sesh/sesh.toml"

[[session]]
name = "aerospace config"
path = "~/dotfiles/aerospace"
startup_command = "nvim aerospace.toml"
preview_command = "bat --color=always ~/dotfiles/aerospace/aerospace.toml"

[[session]]
name = "infsem"
path = "~/Documents/Programming/SEMINAR_INF"
startup_command = "pyenv shell 3.9.18"

[[session]]
name = "nvim plugin config"
path = "~/dotfiles/nvim/lua/theprimeagen/lazy"
startup_command = "nvim {}"

[[session]]
name = "nvim config"
path = "~/dotfiles/nvim/lua/theprimeagen"
startup_command = "nvim {}"

